### ISSUE TITLE
Python version guided filter\mask refine comparison

### ISSUE THREAD

**Issue by Vozf** [xiongzhu666/Sky-Segmentation-and-Post-processing#4]
There is a python implementation which generates noticably different results(noticeable on the border, python version preserves more, while this repo version "damages" the original correct border)
https://github.com/google/sky-optimization/pull/14/files
Are there any major differences between your implementation and the python version and if so how could they be changed?

**Comment by Vozf** [comment]
That notable difference was because of before postprocessing my code resizing differences. Resizing image from 1196x1080 to 1024x1024 gave notable quality degradation.

**Comment by DanielZanchi** [comment]
Did anyone try out the python code provided? 
It gives different results from the ones in the c++ code we see in the examples:
![input](https://github.com/xiongzhu666/Sky-Segmentation-and-Post-processing/assets/6886116/b6825de2-7be4-4f6f-957b-c3805bffe600)
![mask](https://github.com/xiongzhu666/Sky-Segmentation-and-Post-processing/assets/6886116/a863d3c6-d718-4788-800c-44299c95b472)
![output](https://github.com/xiongzhu666/Sky-Segmentation-and-Post-processing/assets/6886116/0b425934-4493-4b66-9179-b6c0fa22b70e)

**Comment by DanielZanchi** [comment]
i solved this issue by removing the rotation at the beginning.
