### ISSUE TITLE
CUDA Out of Memory with while running Sky segmentation TRT model Inference on GPU A2000

### ISSUE THREAD

**Issue by AnushaManila** [xiongzhu666/Sky-Segmentation-and-Post-processing#9]
Hello,

Thanks for sharing your work on Sky Segmentation.
I converted the ONNX model to TensorRT and I'm able to run inference on a Video but only for about 90 seconds.
Then I see CUDA Runtime Error 2 (Out of Memory)

Environment:
- TensorRT Version: 8.6.1.6
- NVIDIA GPU: A2000
- NVIDIA Driver Version: 510.39.01
- CUDA Version: 11.6
- CUDNN Version: 8.9.4
- Operating System: Ubuntu 20.04
- Python Version : 3.8.10

Steps To Reproduce:
Step1: Download the ONNX file from Sky-Segmentation and Post processing Git Repo or the link [here](https://drive.google.com/drive/folders/1TqFb-0XTLCuXbKvXQ0W7vOnkhOi7rT-n)

Step2: Convert ONNX to TRT using the repo [TensorRT-Alpha](https://github.com/FeiYull/TensorRT-Alpha)

Step3: Run inference on a video using the script [U2-Net TensorRT](https://github.com/NobuoTsukamoto/tensorrt-examples/blob/main/python/u2net/trt_u2net.py)

Error Encountered after approx. 90 seconds:
![image](https://github.com/xiongzhu666/Sky-Segmentation-and-Post-processing/assets/12676003/a606acd8-0ebe-4928-89e8-77adadc854fe)

Any idea what could have caused this?

**Comment by xiongzhu666** [comment]
> Hello,
> 
> Thanks for sharing your work on Sky Segmentation. I converted the ONNX model to TensorRT and I'm able to run inference on a Video but only for about 90 seconds. Then I see CUDA Runtime Error 2 (Out of Memory)
> 
> Environment:
> 
> * TensorRT Version: 8.6.1.6
> * NVIDIA GPU: A2000
> * NVIDIA Driver Version: 510.39.01
> * CUDA Version: 11.6
> * CUDNN Version: 8.9.4
> * Operating System: Ubuntu 20.04
> * Python Version : 3.8.10
> 
> Steps To Reproduce: Step1: Download the ONNX file from Sky-Segmentation and Post processing Git Repo or the link [here](https://drive.google.com/drive/folders/1TqFb-0XTLCuXbKvXQ0W7vOnkhOi7rT-n)
> 
> Step2: Convert ONNX to TRT using the repo [TensorRT-Alpha](https://github.com/FeiYull/TensorRT-Alpha)
> 
> Step3: Run inference on a video using the script [U2-Net TensorRT](https://github.com/NobuoTsukamoto/tensorrt-examples/blob/main/python/u2net/trt_u2net.py)
> 
> Error Encountered after approx. 90 seconds: ![image](https://private-user-images.githubusercontent.com/12676003/288549166-a606acd8-0ebe-4928-89e8-77adadc854fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDA5ODksIm5iZiI6MTcwMjAwMDY4OSwicGF0aCI6Ii8xMjY3NjAwMy8yODg1NDkxNjYtYTYwNmFjZDgtMGViZS00OTI4LTg5ZTgtNzdhZGFkYzg1NGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZTI4MWU1ZWQ3YzRlNzQzNWNlNmYxNTVlZjRmYTIzMTIwMjgxMGZmNGQzZTRlNTc3NTkwYTdmNzIwNzdjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ugVfduofrG29v3XOihN7Z3TJBpCgJW0viWC5nbyoCtU)
> 
> Any idea what could have caused this?

I didn‘t deploy by tensorRT，but your speed test is unreasonable. the U2Net inference speed is about 25ms by pytorch and the tensorRT should be more faster. you can refer to other repo and check you tensorRT environment

**Comment by AnushaManila** [comment]
The inference speed is not the problem, it is realtime with TensorRT.
Issue is that the CUDA out of memory happens after running the inference for 90 seconds long.

**Comment by AnushaManila** [comment]
Found out that Generating the TensorRT Model using [this ](https://github.com/NobuoTsukamoto/tensorrt-examples/blob/main/python/detection/convert_onnxgs2trt.py)script works all fine
Not sure what is wrong with the model generated using /Tensorrt-8.6.1.6/trtexec as in [here ](https://github.com/FeiYull/TensorRT-Alpha/tree/main/u2net)though
Closing this issue
